services:
  students-get-service:
    build: .
    container_name: students-get-service
    ports:
      - "8081:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - mongo-network

networks:
  mongo-network:
    external: true
    name: mongo-network

